name: "Fetch base branch"
description: "Fetches base branch, but leaves head checked out"

runs:
  using: "composite"
  steps:
    - name: Fetch Base Branch
      shell: bash
      run: |
        git fetch origin $GITHUB_BASE_REF
        git fetch origin $GITHUB_HEAD_REF
        git checkout $GITHUB_BASE_REF
        git checkout $GITHUB_HEAD_REF