name: "Compress and upload reports"
description: "Compresses all reports, and uploads the artifacts"

inputs:
  artifact-name:
    required: true

runs:
  using: "composite"
  steps:
    - name: Compress Reports
      continue-on-error: true
      if: ${{ always() }}
      shell: bash
      run: ./gradlew compressReports

    - name: Upload Reports
      continue-on-error: true
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: reports/*.zip