[versions]
# Android SDK
#noinspection UnusedVersionCatalogEntry
compileSdk = "36"
#noinspection UnusedVersionCatalogEntry
minSdk = "23"
#noinspection UnusedVersionCatalogEntry
targetSdk = "36"

# Dependencies
agp = "8.13.2"
dokkaGradlePlugin = "2.0.0"
kotlin = "2.0.21"
lint = "31.10.1" # should be agp+23 (31.13.2), but lint 31.11+ was compiled with Kotlin 2.2 — incompatible with Kotlin 2.0.21
mockk = "1.13.13"
rhino = "1.8.1"

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidx-annotations = "androidx.annotation:annotation:1.10.0"
app-androidx-core = "androidx.core:core-ktx:1.18.0" # 1.19.0+ requires AGP 9.1.0+
app-androidx-appcompat = "androidx.appcompat:appcompat:1.7.1"
app-androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.2.1"
app-androidx-fragment = "androidx.fragment:fragment-ktx:1.8.9"
app-androidx-lifecycle-viewmodel = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.11.0"
app-material = "com.google.android.material:material:1.14.0"
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokkaGradlePlugin" }
eclipse-jgit = "org.eclipse.jgit:org.eclipse.jgit:6.10.0.202406032230-r"
kotlin-gradle-jvm = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }
rhino = { module = "org.mozilla:rhino", version.ref = "rhino" }
test-androidx-core = "androidx.test:core-ktx:1.6.1"
test-androidx-junit = "androidx.test.ext:junit:1.2.1"
test-androidx-runner = "androidx.test:runner:1.6.2"
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0"
kotlinx-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.0"
test-kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.8.0"
test-junit = "junit:junit:4.13.2"
test-mockk-jvm = { module = "io.mockk:mockk", version.ref = "mockk" }
test-mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
test-okhttp-webserver = "com.squareup.okhttp3:mockwebserver:4.3.1"
test-robolectric = "org.robolectric:robolectric:4.13"

[plugins]
android-application = { id = "com.android.application" }
android-library = { id = "com.android.library" }
android-lint = { id = "com.android.lint" }
java = { id = "java-library" }
kotlin-android = { id = "org.jetbrains.kotlin.android" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm" }
tealium-gradle = { id = "tealium-plugin" }
tealium-library = { id = "tealium-library" }
tealium-dokka-root = { id = "dokka-root" }
tealium-dokka-library = { id = "dokka-library" }
tealium-bom = { id = "tealium-bom" }
