package com.tealium.tests.common

import com.tealium.prism.core.api.data.DataObject
import com.tealium.prism.core.api.rules.Condition
import com.tealium.prism.core.api.rules.Rule
import com.tealium.prism.core.api.transform.TransformationScope
import com.tealium.prism.core.api.transform.TransformationSettings
import com.tealium.prism.core.api.transform.TransformationSettingsBuilder
import com.tealium.prism.core.internal.rules.conditionConverter

private typealias Keys = TransformationSettings.Converter

/**
 * Convenience method to retrieve the transformationId from the [DataObject] generated by [TransformationSettingsBuilder.build]
 */
val TransformationSettingsBuilder<*>.id: String
    get() = build().getString(Keys.KEY_TRANSFORMATION_ID)!!

/**
 * Convenience method to retrieve the scope from the [DataObject] generated by [TransformationSettingsBuilder.build]
 */
val TransformationSettingsBuilder<*>.scope: TransformationScope?
    get() = build().get(Keys.KEY_SCOPE, TransformationScope.Converter)

/**
 * Convenience method to retrieve the configuration from the [DataObject] generated by [TransformationSettingsBuilder.build]
 */
val TransformationSettingsBuilder<*>.configuration: DataObject
    get() = build().getDataObject(Keys.KEY_CONFIGURATION)!!

/**
 * Convenience method to retrieve the conditions from the [DataObject] generated by [TransformationSettingsBuilder.build]
 */
val TransformationSettingsBuilder<*>.conditions: Rule<Condition>?
    get() = build().get(Keys.KEY_CONDITIONS, conditionConverter)

/**
 * Convenience method to convert any [TransformationSettingsBuilder] into [TransformationSettings]
 * instance.
 *
 * All [TransformationSettings] required properties must be set, or this will throw
 */
fun TransformationSettingsBuilder<*>.buildTransformationSettings(): TransformationSettings =
    TransformationSettings.Converter.convert(build().asDataItem())!!
